# Docker Compose configuration for Firestore Clone
version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: firestore-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: Ponceca120
      MONGO_INITDB_DATABASE: firestore_clone
    volumes:
      - mongodb_data:/data/db
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - firestore-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  firestore-clone:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: firestore-clone-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      SERVER_HOST: 0.0.0.0
      SERVER_PORT: 3000
      MONGODB_URI: mongodb://admin:Ponceca120@mongodb:27017/firestore_clone?authSource=admin
      DATABASE_NAME: firestore_clone
      JWT_SECRET: your-super-secure-jwt-secret-change-in-production
      JWT_EXPIRATION: 24h
      BCRYPT_COST: 12
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: redispassword
      REDIS_DB: 0
      REDIS_MAX_RETRIES: 3
      REDIS_POOL_SIZE: 10
      REDIS_CONN_MAX_IDLE_TIME: 30m
      REDIS_CONN_MAX_LIFETIME: 1h
      WEBSOCKET_PATH: /ws/v1/listen
      CLIENT_SEND_CHANNEL_BUFFER: 10
      LOG_LEVEL: info
      LOG_FORMAT: json
    volumes:
      - ./logs:/app/logs
    networks:
      - firestore-network
    depends_on:
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  redis:
    image: redis:7.2-alpine
    container_name: firestore-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: >
      redis-server 
      --appendonly yes 
      --requirepass redispassword
      --maxmemory 512mb
      --maxmemory-policy allkeys-lru
      --save 900 1
      --save 300 10
      --save 60 10000
    volumes:
      - redis_data:/data
      - ./redis/redis.conf:/etc/redis/redis.conf:ro
    networks:
      - firestore-network
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "redispassword", "ping"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

  mongo-express:
    image: mongo-express:1.0.0
    container_name: firestore-mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: Ponceca120
      ME_CONFIG_MONGODB_URL: mongodb://admin:Ponceca120@mongodb:27017/
      ME_CONFIG_BASICAUTH: false
    networks:
      - firestore-network
    depends_on:
      mongodb:
        condition: service_healthy
    profiles:
      - development

  nginx:
    image: nginx:1.25-alpine
    container_name: firestore-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./logs/nginx:/var/log/nginx
    networks:
      - firestore-network
    depends_on:
      - firestore-clone
    profiles:
      - production

networks:
  firestore-network:
    driver: bridge
    name: firestore-network

volumes:
  mongodb_data:
    name: firestore_mongodb_data
  redis_data:
    name: firestore_redis_data